# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'personalFinances' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for personalFinances
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'

  target 'personalFinances-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'personalFinancesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'personalFinances-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
